### ISSUE TITLE
Unexpected Characater encountered

### ISSUE THREAD

**Issue by mcloum** [EDDiscovery/EDDLite#2]
Scanning system

`05/09/3306 21:33:36 Fuel Scoop: 4.9t, Total:31.9t
05/09/3306 21:33:59 Detailed scan of A 4: Sudarsky Class I Gas Giant, Mass:137.1EM, Gravity:1.48G, Radius:61303.5km, Dist:9318.1ls, Name:Wredguia TU-Z b13-0 A 4
Sent Scan event to EDDN (Detailed scan of A 4)
Error sending EDSM events Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: W. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at EliteDangerousCore.EDSM.EDSMClass.SendJournalEvents(List`1 entries, String& errmsg) in C:\Code\EDDLite\EliteDangerousCore\EliteDangerous\EDSM\EDSMClass.cs:line 1050
05/09/3306 21:34:27 Detailed scan of A 2: Icy Body, Mass:0.87EM, Methane Rich Atmosphere, Gravity:0.63G, Radius:7464.9km, Dist:497.1ls, Name:Wredguia TU-Z b13-0 A 2
Sent Scan event to EDDN (Detailed scan of A 2)
`

**Comment by robbyxp1** [comment]
Thanks for the report, i'm guessing its something in the scan data which upset the program, as given to us in the event by frontier.

I'll keep this in mind, but the whole json system is going to be replaced in here, so its not worth investigating further unless it happens on every event.
